/*
  Producer/Consumer problem using the modified SSemaphore class
  with non-private semaphores
*/

#include <iostream>
#include <cstdio>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include "SSemaphore.h"

#define BUFFER "./buffer"

using namespace std;

enum { READ, MADE };

int main(int argc, char *argv[]) {
    FILE *fptr;
    pid_t c_pid;
    key_t ipc_key;
    int producer = 0;
    int i, n, sleep_time;
    
    if (argc != 2) {
        cerr << "Usage: " << argv[0] << " sleep_time" << endl;
        return 1;
    }
    
    sleep_time = atoi(argv[1]);
    
    ipc_key = ftok(".", 'S');
    if (ipc_key == -1) {
        perror("ftok");
        return 1;
    }
    
    SSemaphore sem(ipc_key, 2);
    
    if (sem.IsCreator()) {
        producer = 1;
        sem.Put(1, READ);
        sem.Put(0, MADE);
        cout << "Producer starting (PID: " << getpid() << ")" << endl;
    } else {
        producer = 0;
        cout << "Consumer starting (PID: " << getpid() << ")" << endl;
    }
    
    if (producer == 1) {
        srand((unsigned) getpid());
        
        for (i = 0; i < 10; i++) {
            sleep(sleep_time);
            n = rand() % 99 + 1;
            cout << "A. The number [" << n << "] generated by producer" << endl;
            
            sem.P(READ);
            
            if ((fptr = fopen(BUFFER, "w")) == NULL) {
                perror(BUFFER);
                return 5;
            }
            fprintf(fptr, "%d\n", n);
            fclose(fptr);
            
            cout << "B. The number [" << n << "] deposited by producer" << endl;
            
            sem.V(MADE);
        }
        
        sleep(5);
        cout << "Producer finished. Semaphore will be removed on exit." << endl;
    }

    else {
        c_pid = getpid();
        
        for (i = 0; i < 10; i++) {
            sleep(sleep_time);
            
            sem.P(MADE);
            
            if ((fptr = fopen(BUFFER, "r")) == NULL) {
                perror(BUFFER);
                return 9;
            }
            fscanf(fptr, "%d", &n);
            fclose(fptr);
            
            cout << "C. The number [" << n << "] obtained by consumer " 
                 << c_pid << endl;
            
            sem.V(READ);
        }
        
        cout << "Consumer finished" << endl;
    }
    
    return 0;
}